"Programming
"SQLF
#0789
$serial.sys
(0000h
(00h
(00h-03h)
(01h,05h,06h,0Dh)
(80286+)
(DOS
(ETHDEV.SYS)
(Hercules
(PROF.COM/VPROD.386)
(RAM-MAN/386)
(Table 00
(adapter
(big-endian) TP_ID
(big-endian) conversation ID
(big-endian) error code (see
(big-endian) last record seen (0000h on first call)
(big-endian) logical connection number
(big-endian) logical unit
(big-endian) n
(big-endian) object ID
(big-endian) object ID of queue
(big-endian) primary return code (see
(big-endian) return code (see
(big-endian) type of object
(c)
(call) 0000h (no results returned)
(call) size of following results record (max
(currently
(default
(default)
(e.g.
(for
(function
(length
(max
(none)
(return) ???
(return) status: 0000h if successful, FFFFh on error
(see
(subfunction
(successful)
(usually
----
---- -
---- - APL*PLUS/PC -
---- - DR Multiuser DOS - "
---- - I
---- - IBM ROM BASIC - used while in interpreter
---- - STSC APL*PLUS/PC - MAY BE USED IN FUTURE RELEASES
---- - reserved for user interrupt
---------------------------------------------
---class 05h function
---function
.    640x480
.    800x600
.   1024x768
.  Avance Logic AL2101
.  Compaq QVision 1024/1280
.  Genoa SuperEGA BIOS 3.0+
.  NEL Electronics BIOS
0   0   0   0   0 HDS DS1 DS0
0.9+
00--
0000h
0000h successful
0000h:0000h
0001
0001h
0001h (length of following data)
0001h success
0002h
0002h (length of following data)
0003
0003h
0004h
0005h (length of following data)
0026h/Subfunction
00h
00h  8 BYTEs
00h 12 BYTEs
00h handle is DWORD on top of stack
00h not installed
00h not installed, OK to install
00h successful
01--
01h
01h not installed, not OK to install
02--
02h
03--
03h
04--
04h
05--
05h
06--
06h
06h  N BYTEs
07h
08h
09--
09h
0Ah
0Ch
0Ch (DV 2.26+) default window of task owning handle on top of stack
0Eh
1 if MC_ (mapped conversation) form of verb
1.0+
1.02+
1024x768
10NET
10h
12--
12h
13 06-- Format of Future Domain SCSI defect
132x25
14h
15 DE2E Format of Function 0026h/Subfunction 00
16-bit
16/256K  .   B800 Trident TVGA 8800/8900
1989,1990,1991,1992,1993,1994
2 WORDs unused dummies (for calls from high level languages)
21 0F-- Format of FCB reserved field for DOS
21 4402 Call WORKGRP function 0
21 4402 Format of NDIS request block for
21 440C Format of parameter block for function
21 440D Format of parameter block for function
21 E1-- Format of NetWare reply buffer:
21 E1-- Format of NetWare request buffer:
21 E2-- Format of NetWare reply buffer:
21 E2-- Format of NetWare request buffer:
21 E3-- Format of NetWare reply buffer:
21 E3-- Format of NetWare request buffer:
21 E3-- Values for NetWare function status:
21 F216 Format of NetWare request buffer:
21 F217 Format of NetWare reply buffer:
21 F217 Format of NetWare request buffer:
21/AH=3Fh"BW-TCP",INT
21/AH=59h)
2780 - Novell DOS 7 - EMM386.EXE - MULTITASKING API
2F CB12 Bitfields for Connection CoProcessor
32-bit
386/DOS-Ext
386/DOS-Extender
386MAX
42á
4402
4B--
61 0001 Format of VINES argument block for
61 0001 Format of VINES control block for subfunction 000
61 0002 Format of argument block for BH=
61 0003 Format of VINES argument block for Function 0003h subfunction 0
61 0003 Format of VINES argument block:
61"PC/TCP")
61"PC/TCP",INT
61/AH=00h"PC/TCP",INT
640x400
640x480
67 5BF4 Bitfields for RM386 global flags
6A 0001 Format of record
7A20 - Novell NetWare - DOS Requester v1.03+ - GET ??? ENTRY POINT
7C 0015 Format of SK-UPPS media-specific statistics for
8/7/94
80"BASIC",INT
800x600
8514/A and compatible video cards (e.g. ATI Graphics Ultra)
8x16  640x480
8x16 1024x768
8x8   800x600
94 ---- Format of PCM driver parameters:
95LX
= G    .
= G 128x48
= T 132x25
???
A000
ACTIVE
ADDRESS
AH = 00h
AH = 01h
AH = 03h
AH = 04h
AH = 05h
AH = 12h
AH = E3h
AH = error code (
AH = status
AH = status (00h,80h,81h,84h
AH = status (see
AH = status code (see
AH bit 7 clear if successful
AH bit 7 set on error
AH destroyed
AH=59h)
AH=C0h to AH=FFh, selected by commandline switch
AH=C0h to AH=FFh, selected by scanning AH=D2h-FFh, then AH=C0h-D1h
AH=C0h to AH=FFh, selected by scanning for first free multiplex number
AH=FEh,INT 21/AH=3Fh"BW-TCP",INT 63"BW-TCP",INT 64"BW-NFS"
AL <> 7Fh if not supported
AL = 7Fh if supported
AL = ???
AL = FFh if installed
AL = adapter number
AL = character
AL = error code
AL = error code (see
AL = function
AL = new state (00h disabled, 01h enabled)
AL = status
AL = status (00h,C6h) (see
AL = status (see
AL = subfunction
ALLOCATE
ALTERNATE
AND
API
APL*PLUS/PC
APPC/PC
APPEND
APPLICATION
ARTICOM
ASCII
ASCIZ
ASYNCHRONOUS
ATTRIBUTES
AVAILABLE
AVATAR.SYS
AWARD AT BIOS and AMI 386sx BIOS have been extended to handle more
AX = 0000h
AX = 0000h if installed
AX = 0000h successful
AX = 0001h
AX = 0003h
AX = 2
AX = ???
AX = DOS error code (see
AX = E
AX = FB42h
AX = FFFFh
AX = completion code (see
AX = error code
AX = error code (0
AX = error code (0000h if successful)
AX = error code (00h, 74h, 166h, 167h, 1B4h) (see
AX = error code (01h,05h,06h,0Dh) (see
AX = error code (05h,06h) (see
AX = error code (see
AX = error code (see INT 61"PC/TCP")
AX = number of bytes actually read
AX = number of bytes actually transferred
AX = number of bytes actually written
AX = number of characters
AX = status
AX = status (0000h successful)
AX = status (see
AX destroyed
AX=0000h
AX=0001h
AX=C000h"PCACHE"
Access
Adaptec 154xB/154xC SCSI adapter.
Added
Added by Ralf Brown,
Advanced
All of these addresses show a readout of FF in initial state.
Alloy
Alloy NTNX
Applications
Attachmate
AutoBraille
AutoBraille is a shareware text-to-braille converter by KANSYS, Inc.
B800
BACKGROUND
BASIC
BASIC.COM/BASICA.COM
BASIC.COM/BASICA.COM do not restore vector on termination
BFDE - DESQview/X 1.02+ - DVDOS4GX.DVR -
BH = device/function number (bits 7-3 device, bits 2-0 func
BH = driver number (01h = FM, 02h=DDBV, 03h=memvoice, 05h=MIDI)
BINDERY
BIOS
BIOSes
BL = ???
BL = drive number (00h = default, 01h = A:, etc
BL = socket number (01h to maximum supported by adapter)
BLOCK
BROADCAST
BUFFER
BW-TCP
BX = 0000h
BX = 0000h (indicates special request)
BX = ???
BX = file handle
BX = file handle for device "
BX = network descriptor
BX = number of
BX = segment of resident code
BX = size of parameter block in words (000
BX destroyed
BYTE
BYTEs
Banyan
Beame&Whiteside
Beame&Whiteside's
Bit(s)
Bitfields
Bitfields for
Block
Block:
Borland
Brown
Brown,
C000
CAPTURE
CD-ROM
CF clear
CF clear if successful
CF clear on success
CF set on error
CH = printer number (00h LPT1, 01h LPT2, 02h LPT3)
CHANGE
CHANNEL
CHARACTER
CHECK
CLEAR
CLIPBOARD
CLOCK/CALENDAR
CLOSE
CODE
COMM-DRV
COMM-DRV is a universal serial communications driver by Willies'
COMMAND
COMMAND.COM
COMMUNICATIONS
CONFIGURATION
CONNECTION
CONSOLE
CONTROL
CONTROLLER
CONVERT
COURIERS.COM
CPU-generated
CREATE
CRITICAL
CURRENT
CURSOR
CX = 0000h
CX = ???
CX = length of request buffer in bytes
CX = number of bytes
CX = number of bytes to read
CX = number of bytes to write
CX = number of characters
CX = selector of DPMILOAD data (see
CX = size of buffer
CX:DX -> parameter block (see
Call
Carousel
Category: * - reserved (and not otherwise classified)
Category: - - (none)
Category: A - applications
Category: B - BIOS
Category: C - CPU-generated
Category: D - DOS kernel
Category: E - DOS extenders
Category: F - FAX
Category: G - debuggers/debugging tools
Category: H - hardware
Category: I - IBM workstation/terminal emulators
Category: J - Japanese
Category: K - keyboard enhancers
Category: M - mouse/pointing device
Category: N - network
Category: O - other operating systems
Category: P - printer enhancements
Category: Q - DESQview/TopView and Quarterdeck programs
Category: R - remote control/file access
Category: S - serial I/O
Category: T - DOS-based task switchers/multitaskers
Category: U - resident utilities
Category: V - video
Category: W - MS Windows
Category: X - expansion bus BIOSes
Category: a - access software (screen readers, etc)
Category: b - vendor-specific BIOS extensions
Category: c - caches/spoolers
Category: d - disk I/O enhancements
Category: e - electronic mail
Category: f - file manipulation
Category: g - games
Category: h - vendor-specific hardware
Category: k - file/disk compression
Category: l - shells/command interpreters
Category: m - memory management
Category: n - non-traditional input devices
Category: p - power management
Category: r - runtime support
Category: s - sound/speech
Category: t - TSR libraries
Category: v - virus/antivirus
Category: y - security
Chips&Technologies
Cirrus
Cloaking
Communicating
Communications
Compaq
Computer Software Company, which supports standard INT 14 and
ConcCP/M,DR
Configuration
Connection
Connection Manager by Softwarehouse Corp. permits the sharing of
Control
Controller
Copy to Main
Copyright
Cswitch
DATA
DBLSPACE.BIN
DECnet
DEFAULT
DELETE
DESCRIPTOR
DESKTOP
DESQview
DESQview 2.50-2.52 are distributed as part of DESQview/X v1.0x.
DESQview/TopView
DESQview/X
DETERMINE
DEVICE
DH = session ID (00h for external session managment)
DI = 0
DIRECTORY
DISABLE
DISK
DISPLAY
DL = drive number (80h = first, 81h = second hard disk)
DMA
DOS
DOS-based
DOS/4GW
DPMI
DPMILOAD.EXE
DR-DOS
DRIVE
DRIVEMAP
DRIVEMAP is a redirector which allows drives on computers connected
DRIVER
DS:BX -> argument block (see
DS:DX -> ASCIZ filename
DS:DX -> buffer
DS:DX -> buffer for
DS:DX -> control block (see
DS:SI -> request buffer (see
DVDOS4GX.DVR
DWORD
DX = 0000h
DX = ???
DX = length of reply buffer in bytes
DX = number of
DX = port number
DX = port number (00h-03h) (04h-43h for XAPCM232.SYS)
Data
Desc:
Description
Device
DigiCHANNEL
Digiboard
Directory
Disk
Dispatcher
Domain
DosReadAsynchNmPipe
DoubleDOS
Driver
E2--
E3--
EAX = error code
EAX, EBX, ECX, and EDX may be modified
EISA
EISA Video Programmable Option Select
EISA board product ID (board in slot
EMM386.EXE
EMS
EMULATION
ENABLE
ENABLE/DISABLE
ENTRY
ERROR
ES = segment of
ES:(E)DI = selector:offset of real mode call structure
ES:BX -> buffer for
ES:BX -> variable pointer record (see
ES:DI -> ???
ES:DI -> ASCIZ server name in form "\\machine"
ES:DI -> buffer for
ES:DI -> reply buffer (see
ES:DI buffer filled
ES:SI -> ???
ES:SI -> Event Control Block (see BX=0003h)
EXCEPTION
EXECUTE
EXTENDED
Emulaser
Enhanced
European
Explosiv
Extended
Extensions
External
FB42 - Borland C++ 3.0 DPMILOAD.EXE -
FF-- - Rational Systems DOS/4GW - ???
FF80 - PC Tools v8+ CPTASK -
FFFFh
FFh
FFh installed
FGDRIVER
FGDRIVER is the external video driver for the shareware
FILE
FLAG
FLAGS
FLOATING
FLUSH
FOR
FOSSIL
FROM
FUNCTION
FUNCTIONS
FaxBIOS
File
FlashTek
Format
Format of
Format of C
Format of D
Format of DESQview
Format of DOS
Format of E
Format of F
Format of FGDRIVER variable pointer record:
Format of NetWare reply buffer:
Format of NetWare request buffer:
Format of VINES argument block:
Function
Future
GET
GET/SET
GNU C/C++ compiler by DJ Delorie and distributed as DJGPP
GO32.EXE is a DOS extender included as part of the 80386 port of the
GPIB (General Purpose Interface Bus, IEEE 488 interface)
GRAPHICS
Graphics
HANDLE
HANDLER
HARDWARE
HUNTER
I/O
IBM
IBM XGA (eXtended Graphics Adapter  8514/A) (
IFSFUNC.EXE
INFO
INFORMATION
INITIALIZATION
INITIALIZE
INPUT
INSTALLATION
INT
INT 10
INT 10 007F - Paradise VGA - ???
INT 10 007F - VIDEO - Paradise VGA, AT&T VDC600 -
INT 10 12-- - Cirrus Logic BIOS v3.02 - LCD panel -
INT 10 12-- - Tseng ET-4000 BIOS v3.00 and v8.00 - BUG
INT 10 12-- - VIDEO - ALTERNATE FUNCTION SELECT (VGA
INT 10 7F03 - SOLLEX SuperVGA - VIDEO SUPPORT CONTROL -
INT 10 7F04 - SOLLEX SuperVGA - POWER CONTROL -
INT 11 0225 - Blank-It Screen Blanker -
INT 13
INT 14
INT 15
INT 15 12-- - DESQview v2.50+ - SEND MESSAGE 0
INT 15 12-- - DESQview v2.50+ - SEND MESSAGE 1
INT 15 12-- - TopView - SEND MESSAGE - "SUBFROM" -
INT 15 5307 - Advanced Power Management Specification - S
INT 15 BFDE - DESQview/X 1.02+ - DVDOS4GX.DVR -
INT 15 BFDE - DESQview/X 1.02+ - DVDOS4GX.DVR - ???
INT 15 BFDE - DESQview/X 1.02+ - DVDOS4GX.DVR - GET ???
INT 15/AX=4DD4h,INT 61"HP 95LX",INT 62"HP 95LX"
INT 16
INT 16 FF80 - PC Tools v8+ CPTASK - GET
INT 16 FFA3 - PC Tools v7-8 DATAMON, v9+ DPROTECT - GET ???
INT 16 FFDD - PC Tools v5.1+ PCShell API -
INT 17
INT 1A
INT 20 to INT E0, selected by configuration
INT 21
INT 21 252B - Phar Lap 386/DOS-Extender -
INT 21 4402
INT 21 4B--
INT 21 52--
INT 21 64-- - OS/2 v2.1+ Virtual DOS Machine - GET
INT 21 64-- - OS/2 v2.1+ Virtual DOS Machine - OS/2 API
INT 21 DF-- - Novell NetWare - PRINT SERVICES -
INT 21 E1-- - Novell NetWare - MESSAGE SERVICES -
INT 21 E2--
INT 21 E2-- - Novell NetWare - DIRECTORY SERVICES -
INT 21 E3--
INT 21 E3-- - Novell NetWare - ACCOUNTING SERVICES -
INT 21 E3-- - Novell NetWare - BINDERY SERVICES -
INT 21 E3-- - Novell NetWare - CONNECTION
INT 21 E3-- - Novell NetWare - FILE SERVER -
INT 21 E3-- - Novell NetWare - QUEUE SERVICES -
INT 21 E3-- - Novell NetWare - QUEUE SERVICES - CHANGE
INT 21 FF-- - Rational Systems DOS/4GW -
INT 21 FF-- - Rational Systems DOS/4GW - ???
INT 21/AH=
INT 2A
INT 2C
INT 2F
INT 2F 2780 - Novell DOS 7 - EMM386.EXE - MULTITASKING API
INT 2F 3901 - Kingswood TSR Windows -
INT 2F 4310
INT 2F 6284 - PC Tools v7-8 DATAMON, v9+ DPROTECT
INT 2F 7A20 - Novell NetWare - DOS Requester v1.03+ - GET ??? ENTRY POINT
INT 2F 7A20 - Novell NetWare - DOS Requester v1.03+ - GET VLM
INT 2F C000
INT 2F DE01 - DESQview v2.26+ XDI - CUSTOM SUBFUNCTION,
INT 2F FB-- - AutoBraille v1.1A - SET ???
INT 2F FB42 - Borland C++ 3.0 DPMILOAD.EXE -
INT 2F FB42 - Borland C++ 3.0 DPMILOAD.EXE - ???
INT 2F/AX=
INT 31
INT 33
INT 33 256C - LOGITECH MOUSE - SET PARAMETERS - SET
INT 5B 8485 - SitBack v3.02R -
INT 60
INT 60 ----
INT 60 ---- - HP 95LX System Manager -
INT 60 ---- - HP 95LX System Manager - "
INT 60 ---- - HP 95LX System Manager - "M_
INT 60 ---- - HP 95LX System Manager - CLOCK/CALENDAR SERV
INT 60 ---- - HP 95LX System Manager - CLOSE
INT 61
INT 61 0003
INT 61 0003 - Banyan VINES - ASYNC TERMINAL EMULATION -
INT 61 is the default interrupt; the actual interrupt number can be
INT 61"PC/TCP",INT 61/AH=00h"PC/TCP"
INT 61"PC/TCP",INT 61/AH=00h"PC/TCP",INT 61/AH=
INT 62
INT 63
INT 65 ---- - Ad Lib SOUND.COM -
INT 65 ---- - Media Vision FM.COM v4.1a+ -
INT 66
INT 67
INT 68
INT 68 01-- - APPC/PC - NETWORK DEVICE CONTROL -
INT 68 02-- - APPC/PC - CONNECTION CONTROL -
INT 6F
INT 7A
INT 7A ---- - Novell NetWare - IPX Driver -
INT 7A ---- - Novell NetWare - IPXODI v2.12+ -
INT 7A ---- - Novell NetWare - SPX Driver -
INT 7A 09-- - IBM 3270 Workstation Program API -
INT 7F
INT 7F 10-- - Alloy NTNX, MW386 - CHANNEL CONTROL -
INT 80 ---- - SoundBlaster SBFM driver -
INT 80"BASIC",INT
INT 94 ---- - Media Vision PCM.COM - GET
INT 94 ---- - PCM driver - INITIALIZE
INT E0
INTERFACE
INTERNAL
INTERRUPT
IOCTL
Inc.
Index:
Information
Inp.:
Intel
Interconnections
Interface
Interrupt
Interrupt List      Release 42      Last change 8/7/94
Interrupts
Japanese
KEYBOARD
KEYSTROKE
Kingswood
LAN
LANtastic
LOCAL
LOGICAL
LOGITECH
Lahey FORTRAN use this interrupt
Lap
LaserTools; it may use either memory or disk space to spool output
Last
List
Logic
MANAGER
MBBIOS
MDEBUG
MEMORY
MESSAGE
MODE
MOUSE
MS-DOS
MULTITASKING
MW386
Machine
Main
Management
Manager
Master
Media
Memory
Michael
Microsoft
Model
Mouse
MultiDOS
Multiuser
NAME
NETWORK
NOTE: used only when PS/2 style password is NOT in effect.
NOTIFICATION
NTNX
NTNX,
NUMBER
Nanosoft,
NetBIOS
NetWare
NetWare,
Network
Note:
Notes:
Novell
OBJECT
OPCODE
OPEN
ORIGINAL
OS/2
OS/386
OUTPUT
Offset
Olivetti
Organizer
PAGE
PARAMETER
PARAMETERS
PC Tools PC-Cache 5.x and Qualitas Qcache 4.00 are OEM versions of
PC radio by CoZet Info Systems
PC-Cache
PC-Kwik
PC-MOS/386
PC-MOS/386 is a multitasking/multiuser MS-DOS-compatible operating
PC-MOS/386 v5.01 is a multitasking, multiuser MS-DOS 5.0-compatible
PC/TCP
PCACHE is the resident print spooler portion of PrintCache by
PCACHE.EXE
PCM.COM
PCMCIA
PCROBOTS
PHYSICAL
POINT
POINTER
PORT
POSITION
POWER
PRIMITIVES
PRINT
PRINTER
PROCEDURE
PROCESS
PROCESSING
PROCESSOR
PROGRAM
PROTECTED-MODE
PROTOCOL
Packet
Paradise
Parameter
PenDOS
Personal
Phar
Philips CD-ROM player CM50
Plus
Power
PrintCache
Processing
Program
Program:
Protocol
QUEUE
QUICKCACHE
Quarterdeck
READ
RECEIVE
RECEIVER.COM
RECORD
RECOVERY
REDIRECTOR
REGION
REGISTER
REGISTERS
RELEASE
RELEASES
RELOCATED
REMOTE
REMOVE
REQUEST
RESERVED
RESET
RESIDENT
RESTORE
RETURN
RM386
RM386 traps this function on the initial transition to protected
ROM
Ralf
Range:
Rational
Register
Release
Requester
Return:
S3 86C928 video controller (ELSA Winner 1000)
SCREEN
SCSI
SDA CDS pointer -> current directory structure for drive with
SDA first filename pointer -> fully-qualified
SEGMENT
SELECT
SELECTOR
SEMAPHORE
SEND
SERIAL
SERVER
SERVICE
SERVICES
SESSION
SET
SETDRVER.COM
SFT DPB field -> DPB of drive containing file
SI = 4358h
SI = TSR reply (lowercase version of entry SI, i.e. SI
SIZE
SK-UPPS
SK-UPPS is the Schneider & Koch Universal Portable Protocol Stack,
SMARTDRV
SNAP.EXE
SNAP.EXE is a TSR written by IBM and Carnegie Mellon University
SOLLEX
SOUND
SPECIFIC
SPECIFIED
SPECIFY
SS = DOS DS (must be using a DOS internal stack)
STACK unchanged
STACK:
START
STATE
STATISTICS
STATUS
STRING
STSC moved its interrupts from 86h-8Ch to C6h-CCh, but did not delete
SUPPORT
SWITCH
SWITCHING
SYNCHRONIZATION
SYSSVC.COM
SYSTEM
SYS_PROF.EXE is the TSR portion of a profiler from Micro Cornucopia
Screen
SeeAlso:
Server
Service
Services
Shamrock
Shell
Size
Socket
Software
SoundBlaster
SpaceManager
Specification
Standard
Status
Super
Super PC-Kwik, and thus support this call
SuperVGA
Switch-It
System
Systems
TABLE
TARGA.DEV
TASK
TCPIP.SYS
TERMINAL
TERMINATE
TERMINATION
TIME
TIMEOUT
TRANSACTION
TRANSMIT
TSR
Tandy
TaskMAX
Technologies
TelAPI
The Banyan interrupt handler is identified by the string "BANV" in
The I/O address range is dipswitch selectable from:
The image is drawn with its lower left corner at the current graphics
The starting point is the current graphics cursor position; the cursor
This call is ignored in text modes
This compilation is Copyright (c) 1989,1990,1991,1992,1993,1994 Ralf Brown
This function is ignored in text modes
Tools
TopView
TopWare
Toshiba
Tseng
UNINSTALL
USER
Ultra)
UltraVision
VECTOR
VERSION
VGA
VGA-Sync,ET-3000
VIDEO
VINES
VIO handle (must be 00h)
VIRTUAL
VIRUS
Values
Values for
Values for NetWare function status:
Vanderaart
Video
Vinci
Virtual
Vision
Voice:
WINDOW
WINDOWS
WITH
WORD
WORDs
WORKSTATION
WRITE
Windows
Workstation
XAPCM232.SYS)
YEA_GUS.EXE
ZIPKEY
acceleration
access
accessed
active
actual
actually
adapter
additional
address
addresses
after
all
all other flags (except IF) may be modified
allocate
allocated
allocation
allow
allowed
allows
already
also
also supported by Genius Mouse 9.06
alternate
always
an actual INT 2F instruction instead of some simulation such as a
and
another
any
application
applications
appropriate
are
area
argument
array
as that is a licensed version of Disk Spool II
asynchronous
at AH=59h)
at INT 21/AH=59h)
attached
attribute
attributes
attributes:
automatically
available
available only in protected mode
available only in real or V86 mode
available only when popped up
background
because the request is handled on the initial trap to the memory
been
before
beginning
being
between
bit
bits
blank-padded
block
block:
blocks
board
breakpoint
broadcast
buffer
buffer filled
buffer:
buffers
but
button
byte
bytes
bytes)
cache
caches/spoolers
call
callback
called
called by OmniView to notify programs loaded before OmniView of state
called by ROM BASIC
called by ROM BASIC, but pointed at IRET by BASIC.COM/BASICA.COM
called)
caller
caller must be on a workstation which is security-equivalent to a
caller's
calling
callout or callback (usually hooked rather than called)
calls
capabilities
capabilities:
capture
cards
chain
change
changed
channel
character
characters
check
checking
checksum
chipset
clear
client
clock
cluster
code
code in AL (see
code:
color
column
columns
command
commandline
commands
common data (see SYS_LOGOUT above)
communications
compatibility
compatible
compilation
complete
completion
compressed
compression
condition
configuration
connected
connection
connections
consecutive
consecutive interrupt (64h by default) if it is loaded
consists
console
contain
containing
contains
contents
context
control
control block updated
control/file
controller
controllers
conventional
coordinate
coprocessor
copy
corner
corresponding
count
counter
country
create
critical
current
currently
cursor
cylinder
data
data)
data:
debuggers/debugging
debugging
default
defined
delay
description
descriptor
descriptors
desired
destination
destroyed
determine
device
devices
direction
directory
directory handle
disable
disabled
disabled,
disk
diskette
display
displayed
distributed
documentation
documented
does
drive
driver
driver should pass this call to previous handler after processing it
driver should pass this call to previous handler before processing it
drivers
drives
due to an omitted end-of-list marker, these versions of the BIOS will
dummies
during
eMail
each
either
electronic
emulation
emulators
enable
enable/disable
enabled
enabled)
encountered
enhancements
enhancers
entries
entry
entry:
environment
equivalent
error
errors
event
except
exception
executable
execution
expansion
extended
extender
extenders
extension
extensions
external
extracted
failed
failure
far call to the address in the interrupt vector table
feature
field
fields
file
file/disk
filename
files
filled
first
flag
flags
flags:
floating-point
followed
following
for
foreground
format
found
frame
free
from
full
function
function, but redirects the port over the network; if DX is any other
functions
future expansion
generated
get
given
graphics
group
handle
handler
handles
hard
hardware
has
have
header
header:
height
high
hooked
horizontal
host
hotkey
identical
identification
identifier
if CX is not 636Ch on entry, INT 21/AH=6Ch is invoked, because a bug
if DX is 0-3 on entry, Connection Manager emulates the standard BIOS
ignored
image
immediately
implementation
implementations
implemented
in OS/2 1.x FAPI erroneously called AH=64h instead of AH=6Ch
included
including
index
indicates
info
information
information:
initial
initialization
initialized
input
input channel (0-3) for output channel
installation
installation check;
installed
installed,
instance
instead
instruction
insufficient
interface
internal
interpreter
interpreters
interrupt
interrupt;
interrupts
interrupts (62h and 63h by default); the BW-NFS client uses a third
interrupts disabled
interrupts if they were disabled before making the call
into
introduced
invalid
invoked
it provides a full CAM implementation (see INT 4F/AX=8100h)
kernel
keyboard
keystroke
keystrokes
languages)
last
later
left
length
length of following data (max
length of following data (max 1
length of object's name (01h-2Fh)
length-prepended and NULL terminated string for Counter
level
limit
line
linear
list
loaded
local
location
lock
locked
locks on logical record names are advisory and may be ignored by other
logical
longer
machine
mailbox
major
management
manager
manager caused by INT instructions, this API must be invoked with
mapping
mask
maximum
may
may be left dangling by other programs written with the same version
may be masked by setting bit
may not be invoked from within a hardware interrupt handler
members are the Husky Hunter, Husky Hunter 16/80, and Husky Hawk.
memory
message
messages
minimum
minor
mode
mode caused by the INT instruction, which means it can not be
modes
modified
module
monitor
monochrome
more
mouse
mouse/pointing
mshiels@masnet.uucp
multicast
multiple
multiplex
must
name
necessary
network
new
next
non-traditional
nonzero
normal
not
not all vendors include the Tseng TSR which supports these functions
not pop up a "Programming Error" window, instead returning an error
not supported by MS Windows 3.0 DOSX.EXE DOS extender
not supported by MS Windows 3.0 in Standard mode
nothing
notification
number
number of
number of sectors
number:
numbers
object
obsolete (no longer present in current versions)
offset
offset of
one
only
only supported by 32-bit DPMI hosts, but may be used by 16-bit clients
only)
open
opened
operating
operation
original
other
otherwise
output
over the parallel or serial ports to appear as local drives
overridden simply by hooking the interrupt
overwritten
packet
packet:
page
pages
palette
panel
paragraphs
parameter
parameters
parameters:
partially documented function
partition
password
path
pathname
pcANYWHERE
pending
perform
physical
pixel
pixels
point
pointed
pointer
pointer to ???
pointer to IFS open file structure (see
pointer to buffer
pointer to file state record (see INT 60/DI=0500h)
points
popped
port
portion
position
possible
power
present
presentation
preserved
pressed
previous
previously
primary
print
printer
priority
privileges
procedure
process
processes
processing
processor
product
profile
program
programs
protected
protected mode only???
protected-mode
protection
protocol
provided
provides
purposes
queue
ralf@telerama.lm.com
range
rather
read
read/write
real-mode
receive
received
record
record:
records
redirection
redirector
reference
region
register
registers
release
relocated
relocation
remaining
remote
removed
reply
request
requested
requests
required
reserved
reserved (0)
reset
resident
resolution
resource
response
restore
result
results
results are unpredictable at other times
return
returned
returning
returns
revision
routine
running
runtime
same
scan
screen
screen saver;AD-DOS
search
second
seconds
section
sector
sectors
security
segment
segment address of previous header block (0000h if first)
select
selected
selector
selector:offset
semaphore
send
sequence
serial
serial port, description same as 03F8
serial ports over an IPX or NetBIOS-based network
series
server
service
services
session
session ID (00h)
set
setting
shared
shareware
sharing
shells/command
shift
should
should not be called from within a hardware interrupt handler to avoid
signal
signature
signature byte "H" if allocated from system memory pool
since
single
size
slot
socket
software
some
sound/speech
source
space
special
specification
specified
specify
spooler
stack
stack)
standard
start
starting
state
station
statistics
statistics:
status
status:
stored
stream
string
structure
structure size
structure:
structures
subfn
subfunction
subfunctions
subvector:
success
successful
successful)
successful,
successfully
support
supported
supports
switch
switcher
switchers/multitaskers
system
system by The Software Link, Inc.
systems
table
table:
task
task's
terminal
terminated
termination
text
than
than 1024 cylinders by placing bits 10 and 11 of the cylinder number
that
the
the Beame&Whiteside TCP/IP protocol stack uses two consecutive
the Husky Hunter 16 is an 8088-based ruggedized laptop.
the Novell DOS Named Pipe Extender, Banyan VINES, OS/2 Virtual DOS
the RIL is provided by EGA.SYS, the Microsoft Mouse driver, the OS/2
the TMC-950 does not support any Future Domain BIOS calls; instead,
the calling workstation must have console operator privileges
the floating-point emulators in Borland and Microsoft languages and
the four bytes immediately preceding the interrupt handler
the installation check
the installation check consists of
the installation check consists of testing for the signature
the meanings of BL and BH on entry may be exchanged in future
the port number is stored at offset BEh in the Task Control Block
the second through eighth XGAs
this
this API call may be made from within a hardware interrupt handler
this API is only available if AX=12FFh/BX=0EDCh returns successfully;
this call is
this function
this function is
this function is also supported by
this function is also supported by FlashTek X-32VM
this function is also supported by PC-Cache v8.0.
this function is also supported by Vertisoft's Emulaser utility ELSPL,
this function is also supported by XBIOS.COM
this function is also supported by the Genius Mouse 9.06 driver
this function is called by the DOS
this function is called by the DOS 3.1+ kernel
this function is meant to be called immediately after a mode set;
this function is not supported
this function is not supported by Beame&Whiteside's BWPCTCP v3.0a shim
this function is supported by Advanced NetWare 1.0+
this function is supported by Advanced NetWare 1.0+ and Alloy NTNX
this function is supported by Advanced NetWare 1.02+
this function is supported by Advanced NetWare 2.0+
this function is supported by Advanced NetWare 2.1+
this function is supported by NetWare 4.0+ and Advanced NetWare 1.0
this function is supported by NetWare 4.0+, Advanced NetWare 1.0+,
this function is supported by NetWare 4.0+, Advanced NetWare 1.0+, and
this function is supported by NetWare 4.6+, Advanced NetWare 1.0+, and
this function may require up to 1024 byte of stack; it will not enable
this function was added in NetWare 4.0, but was removed some time prior
this function was first introduced with RM386 (RAM-MAN/386) v6.00
this function was introduced by LAN Manager but is also supported by
this interrupt is used to emulate floating-point instructions with
this is the default location for older versions; see INT 50"DESQview"
this is the default, but other INTs may be used (see INT 50"DESQview")
this port is for the first XGA in the system; 211x-217x are used for
this vector is modified but not restored by Direct Access v4.0, and
this vector is overwritten when GO32 starts but is not restored by
this vector is used by some AMI BIOSes to store the
through
ticks
tim@magee.mhs.compuserve.com
time
timeout
timer
to Advanced NetWare 2.15, and is no longer listed in current Novell
tools
total
transaction
transfer
transmit
transmitted
type
type:
unavailable
unchanged
under
under DESQview, only the INT 15h vector and BASIC segment address (the
under the FlashTek X-32 DOS extender, the pointer is in
undocumented
undocumented function
uninstall
unknown
until
unused
update
updated
use
used
user
using
utilities
utility
v1.00
v1.10,
v1.41
v2.05+
v2.26+
v2.50+
v3.03
v4.00+
v4.20
v5.0
v5.01
v5.1-8.0
v5.10+
valid
value
values
variable
vector
vendor-specific
version
versions
vertical
video
virtual
virus/antivirus
volume
waiting
was
when
whether
which
which implements the Simple Network Application Protocol
which provides an API on top of its Data Link Interface, allowing the
while
width
will
window
with
with:
within
without
word
workspace
workstation
workstation/terminal
write
write wraps at end of line and terminates if it reaches end of screen
written
